// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbgkmxliknfczorbrntm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiZ2tteGxpa25mY3pvcmJybnRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDAwNjksImV4cCI6MjA1ODkxNjA2OX0.xzhExi8N9ebYl4c1ETpZJdXW555vh19k34Y-ROrD4pM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);